# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  ########################################
  ### ASSERTIONS: System Requirements
  ########################################
  assertions:
    ### Assertion: OS Version
    ### -------------------------------------
    - resource: Microsoft.Windows.Developer/OsVersion
      id: OsVersion
      directives:
        description: Minimum OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: "10.0.22000"

  ########################################
  ### RESOURCES: System Configuration
  ########################################
  resources:
    ### Enable: Developer Mode
    ### -------------------------------------
    - resource: Microsoft.Windows.Developer/DeveloperMode
      id: DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present

    ### Install: Freedom Scientific JAWS 2023
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: JAWS
      directives:
        description: Freedom Scientific JAWS 2023
        allowPrerelease: true
      settings:
        id: FreedomScientific.JAWS.2023
        source: winget
        ensure: Present

    ### Install: NVAccess.NVDA
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: NVDA
      directives:
        description: Install NVAccess.NVDA
        allowPrerelease: true
      settings:
        id: NVAccess.NVDA
        source: winget
        ensure: Present
    
    ### Install: NotePad++
    ### -------------------------------------
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Notepad++
      directives:
        description: Install Notepad++
        allowPrerelease: true
      settings:
        id: Notepad++.Notepad++
        source: winget
        ensure: Present
  configurationVersion: 0.2.0
